---
flamethrower_grow_util: 20
flamethrower_grow_rate: 0.3
flamethrower_total_particle_life: 400
flamethrower_shrink_after: 55
flamethrower_shrink_rate: 1
flamethrower_starting_size: 2

flamethrower_damping: 0.95
flamethrower_fireball_size: 4
camera_offset:
  x: -480
  y: -270